name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
# Los inputs y outputs son los mismos que en el custom JavaScript action y el código es el mismo.
# Lo que es diferente es como se accede a esos inputs en el código que es ejecutado en el contenedor,
# y como se configuran los outputs en el contenedor.
# Ver deployment.py
inputs:
  bucket:
    description: 'The S3 bucket name'
    required: true
  bucket-region:
    description: 'The region of the S3 bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the deployable files'
    required: true
outputs:
  website-url:
    description: 'The URL of the deployed website'
runs:
  # Obligatorio indicar using: 'docker'. Esto le dice a GitHub Actions que es una custom Docker action
  # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-container-actions
  using: 'docker'
  # Hay que indicar el path. Como está en la misma ruta en este ejemplo, así vale
  image: 'Dockerfile'
